### ISSUE TITLE
Metal detector not automatically showing

### ISSUE THREAD

**Issue by jokernights** [Alivemonstor/al-treasurehunt#2]
I'm assuming after you view the map and you go to the area it's suppose to spawn a metal detector? everything else works because i gave myself a metal detector.. but is there something i'm not doing correctly?

**Comment by Alivemonstor** [comment]
> I'm assuming after you view the map and you go to the area it's suppose to spawn a metal detector? everything else works because i gave myself a metal detector.. but is there something i'm not doing correctly?

you're supposed to have the metal detector before you enter the zone
