### ISSUE TITLE
Spamming while detecting.

### ISSUE THREAD

**Issue by porcelain-doll** [Alivemonstor/al-treasurehunt#3]
Hello! Whenever someone uses the metal detector, they can wait until the progress bar is almost over and hit it again and it'll allow the player to find 3-4 treasure chests in one spot without moving.  Any fix for this? Thank you! Love the script!

**Comment by heyjeay** [comment]
want to update and get more detail on this bug, which i'm not sure if it's been fixed:

**Current outcome:**
When you are using a metal detector in an area marked by a treasure map.. If you "spam" scan after each bar is full you will continuously unbury treasure chests.
It will stop digging chests once you have fully completed opening a chest.
However, if you are spamming it, it never clears you as having opened the chest as you will be constantly opening one.

Expected Outcome: Each spot disappears after digging up one treasure chest, Which means each spot should only contain 1 chest.
1 map = 1 chest

**Steps to reproduce:**
Get a treasure map and read it
Head to location with a metal detector.
Use the metal detector (Hotbar is best) and once the progress bar is done, hit it again (Faster the better)
Keep doing this after each time the bar fills up.

**Comment by Qwerty1Verified** [comment]
#6 Should fix this

**Comment by Alivemonstor** [comment]
#6
